<?php
$section  = 'color_';
$priority = 1;
$prefix   = 'color_';

Businext_Kirki::add_field( 'theme', array(
	'type'     => 'preset',
	'settings' => 'color_preset',
	'title'    => esc_html__( 'Color Preset', 'businext' ),
	'section'  => $section,
	'default'  => '-1',
	'priority' => $priority ++,
	'multiple' => 3,
	'choices'  => array(
		'-1' => array(
			'label'    => esc_html__( 'None', 'businext' ),
			'settings' => array(),
		),
		'01' => array(
			'label'    => esc_html__( 'Preset 01', 'businext' ),
			'settings' => array(
				'primary_color'   => Businext::PRIMARY_COLOR,
				'secondary_color' => Businext::SECONDARY_COLOR,
			),
		),
		'02' => array(
			'label'    => esc_html__( 'Preset 02', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#21C674',
				'secondary_color'                         => '#1F375A',
				'heading_color'                           => '#1F375A',
				'link_color'                              => '#1F375A',
				'link_color_hover'                        => '#21C674',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#21C674',
					'background' => '#21C674',
				),
				'button_hover_color'                      => array(
					'color'      => '#21C674',
					'border'     => '#21C674',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#21C674',
				'navigation_dropdown_border_bottom_color' => '#21C674',
				'search_popup_text_color'                 => '#21C674',
				'search_popup_icon_hover_color'           => '#21C674',
			),
		),
		'03' => array(
			'label'    => esc_html__( 'Preset 03', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#FF8F19',
				'secondary_color'                         => '#1A0272',
				'heading_color'                           => '#1A0272',
				'link_color'                              => '#1A0272',
				'link_color_hover'                        => '#FF8F19',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#FF8F19',
					'background' => '#FF8F19',
				),
				'button_hover_color'                      => array(
					'color'      => '#FF8F19',
					'border'     => '#FF8F19',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#FF8F19',
				'navigation_dropdown_border_bottom_color' => '#FF8F19',
				'search_popup_text_color'                 => '#FF8F19',
				'search_popup_icon_hover_color'           => '#FF8F19',
			),
		),
		'04' => array(
			'label'    => esc_html__( 'Preset 04', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#E50A25',
				'secondary_color'                         => '#222222',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#E50A25',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#E50A25',
					'background' => '#E50A25',
				),
				'button_hover_color'                      => array(
					'color'      => '#E50A25',
					'border'     => '#E50A25',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#E50A25',
				'navigation_dropdown_border_bottom_color' => '#E50A25',
				'search_popup_text_color'                 => '#E50A25',
				'search_popup_icon_hover_color'           => '#E50A25',
			),
		),
		'05' => array(
			'label'    => esc_html__( 'Preset 05', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#21C674',
				'secondary_color'                         => '#222222',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#21C674',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#21C674',
					'background' => '#21C674',
				),
				'button_hover_color'                      => array(
					'color'      => '#21C674',
					'border'     => '#21C674',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#21C674',
				'navigation_dropdown_border_bottom_color' => '#21C674',
				'search_popup_text_color'                 => '#21C674',
				'search_popup_icon_hover_color'           => '#21C674',
			),
		),
		'06' => array(
			'label'    => esc_html__( 'Preset 06', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#FEA001',
				'secondary_color'                         => '#222222',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#FEA001',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#FEA001',
					'background' => '#FEA001',
				),
				'button_hover_color'                      => array(
					'color'      => '#FEA001',
					'border'     => '#FEA001',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#FEA001',
				'navigation_dropdown_border_bottom_color' => '#FEA001',
				'search_popup_text_color'                 => '#FEA001',
				'search_popup_icon_hover_color'           => '#FEA001',
			),
		),
		'07' => array(
			'label'    => esc_html__( 'Preset 07', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#D5214A',
				'secondary_color'                         => '#222222',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#D5214A',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#D5214A',
					'background' => '#D5214A',
				),
				'button_hover_color'                      => array(
					'color'      => '#D5214A',
					'border'     => '#D5214A',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#D5214A',
				'navigation_dropdown_border_bottom_color' => '#D5214A',
				'search_popup_text_color'                 => '#D5214A',
				'search_popup_icon_hover_color'           => '#D5214A',
			),
		),
		'08' => array(
			'label'    => esc_html__( 'Preset 08', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#5F3DCD',
				'secondary_color'                         => '#44D2AC',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#5F3DCD',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#5F3DCD',
					'background' => '#5F3DCD',
				),
				'button_hover_color'                      => array(
					'color'      => '#481ADD',
					'border'     => '#481ADD',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#5F3DCD',
				'navigation_dropdown_border_bottom_color' => '#5F3DCD',
				'top_bar_style_01_link_hover_color'       => '#5F3DCD',
				'search_popup_text_color'                 => '#5F3DCD',
				'search_popup_icon_hover_color'           => '#5F3DCD',
			),
		),
		'09' => array(
			'label'    => esc_html__( 'Preset 08', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#FF8F19',
				'secondary_color'                         => '#222222',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#FF8F19',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#FF8F19',
					'background' => '#FF8F19',
				),
				'button_hover_color'                      => array(
					'color'      => '#FF8F19',
					'border'     => '#FF8F19',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#FF8F19',
				'navigation_dropdown_border_bottom_color' => '#FF8F19',
				'top_bar_style_01_link_hover_color'       => '#FF8F19',
				'search_popup_text_color'                 => '#FF8F19',
				'search_popup_icon_hover_color'           => '#FF8F19',
			),
		),
		'10' => array(
			'label'    => esc_html__( 'Preset 10', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#85B041',
				'secondary_color'                         => '#222222',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#85B041',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#85B041',
					'background' => '#85B041',
				),
				'button_hover_color'                      => array(
					'color'      => '#85B041',
					'border'     => '#85B041',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#85B041',
				'navigation_dropdown_border_bottom_color' => '#85B041',
				'search_popup_text_color'                 => '#85B041',
				'search_popup_icon_hover_color'           => '#85B041',
			),
		),
		'11' => array(
			'label'    => esc_html__( 'Preset 11', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#D93030',
				'secondary_color'                         => '#0B2154',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#D93030',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#D93030',
					'background' => '#D93030',
				),
				'button_hover_color'                      => array(
					'color'      => '#D93030',
					'border'     => '#D93030',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#D93030',
				'navigation_dropdown_border_bottom_color' => '#D93030',
				'search_popup_text_color'                 => '#D93030',
				'search_popup_icon_hover_color'           => '#D93030',
			),
		),
		'12' => array(
			'label'    => esc_html__( 'Preset 12', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#3C54ED',
				'secondary_color'                         => '#0B2154',
				'heading_color'                           => '#0B2154',
				'link_color'                              => '#0B2154',
				'link_color_hover'                        => '#3C54ED',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#3C54ED',
					'background' => '#3C54ED',
				),
				'button_hover_color'                      => array(
					'color'      => '#3C54ED',
					'border'     => '#3C54ED',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#3C54ED',
				'navigation_dropdown_border_bottom_color' => '#3C54ED',
				'search_popup_text_color'                 => '#3C54ED',
				'search_popup_icon_hover_color'           => '#3C54ED',
			),
		),
		'13' => array(
			'label'    => esc_html__( 'Preset 13', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#FFC246',
				'secondary_color'                         => '#222222',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#FFC246',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#FFC246',
					'background' => '#FFC246',
				),
				'button_hover_color'                      => array(
					'color'      => '#FFC246',
					'border'     => '#FFC246',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#FFC246',
				'navigation_dropdown_border_bottom_color' => '#FFC246',
				'top_bar_style_01_link_hover_color'       => '#FFC246',
				'search_popup_text_color'                 => '#FFC246',
				'search_popup_icon_hover_color'           => '#FFC246',
			),
		),
		'14' => array(
			'label'    => esc_html__( 'Preset 14', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#33B412',
				'secondary_color'                         => '#02C9B3',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#33B412',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#33B412',
					'background' => '#33B412',
				),
				'button_hover_color'                      => array(
					'color'      => '#33B412',
					'border'     => '#33B412',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#33B412',
				'navigation_dropdown_border_bottom_color' => '#33B412',
				'top_bar_style_01_link_hover_color'       => '#33B412',
				'search_popup_text_color'                 => '#33B412',
				'search_popup_icon_hover_color'           => '#33B412',
			),
		),
		'15' => array(
			'label'    => esc_html__( 'Preset 15', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#FFD600',
				'secondary_color'                         => '#F73374',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#FFD600',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#FFD600',
					'background' => '#FFD600',
				),
				'button_hover_color'                      => array(
					'color'      => '#FFD600',
					'border'     => '#FFD600',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#FFD600',
				'navigation_dropdown_border_bottom_color' => '#FFD600',
				'top_bar_style_01_link_hover_color'       => '#FFD600',
				'search_popup_text_color'                 => '#FFD600',
				'search_popup_icon_hover_color'           => '#FFD600',
			),
		),
		'16' => array(
			'label'    => esc_html__( 'Preset 16', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#C10E0E',
				'secondary_color'                         => '#14163E',
				'heading_color'                           => '#14163E',
				'link_color'                              => '#14163E',
				'link_color_hover'                        => '#C10E0E',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#C10E0E',
					'background' => '#C10E0E',
				),
				'button_hover_color'                      => array(
					'color'      => '#C10E0E',
					'border'     => '#C10E0E',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#C10E0E',
				'navigation_dropdown_border_bottom_color' => '#C10E0E',
				'search_popup_text_color'                 => '#C10E0E',
				'search_popup_icon_hover_color'           => '#C10E0E',
			),
		),
		'17' => array(
			'label'    => esc_html__( 'Preset 17', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#3556DF',
				'secondary_color'                         => '#222222',
				'heading_color'                           => '#222222',
				'link_color'                              => '#222222',
				'link_color_hover'                        => '#3556DF',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#3556DF',
					'background' => '#3556DF',
				),
				'button_hover_color'                      => array(
					'color'      => '#3556DF',
					'border'     => '#3556DF',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#3556DF',
				'navigation_dropdown_border_bottom_color' => '#3556DF',
				'search_popup_text_color'                 => '#3556DF',
				'search_popup_icon_hover_color'           => '#3556DF',
			),
		),
		'18' => array(
			'label'    => esc_html__( 'Preset 18', 'businext' ),
			'settings' => array(
				'primary_color'                           => '#FF6F47',
				'secondary_color'                         => '#0E236C',
				'heading_color'                           => '#0E236C',
				'link_color'                              => '#0E236C',
				'link_color_hover'                        => '#FF6F47',
				'button_color'                            => array(
					'color'      => '#fff',
					'border'     => '#FF6F47',
					'background' => '#FF6F47',
				),
				'button_hover_color'                      => array(
					'color'      => '#FF6F47',
					'border'     => '#FF6F47',
					'background' => 'rgba(0, 0, 0, 0)',
				),
				'navigation_dropdown_link_hover_color'    => '#FF6F47',
				'navigation_dropdown_border_bottom_color' => '#FF6F47',
				'search_popup_text_color'                 => '#FF6F47',
				'search_popup_icon_hover_color'           => '#FF6F47',
			),
		),
	),
) );

Businext_Kirki::add_field( 'theme', array(
	'type'        => 'color',
	'settings'    => 'primary_color',
	'label'       => esc_html__( 'Primary Color', 'businext' ),
	'description' => esc_html__( 'A light color.', 'businext' ),
	'section'     => $section,
	'priority'    => $priority ++,
	'transport'   => 'auto',
	'default'     => Businext::PRIMARY_COLOR,
) );

Businext_Kirki::add_field( 'theme', array(
	'type'        => 'color',
	'settings'    => 'secondary_color',
	'label'       => esc_html__( 'Secondary Color', 'businext' ),
	'description' => esc_html__( 'A dark color.', 'businext' ),
	'section'     => $section,
	'priority'    => $priority ++,
	'transport'   => 'auto',
	'default'     => Businext::SECONDARY_COLOR,
) );
